{
  "openapi": "3.0.0",
  "info": {
    "title": "Talker Manager API",
    "description": "API construída no curso de desenvolvimento Web da Trybe, que tem como objetivo o aprendizado do modulo FS do Node e como funciona uma API Rest. Consiste um crud de Talkers.",
    "contact": {
      "email": "neto.daniribeiro@gmail.com"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:3333",
      "description": "API de teste"
    },
    {
      "url": "https://defauth98-talker-manager.herokuapp.com/",
      "description": "API de produção"
    }
  ],
  "paths": {
    "/login": {
      "post": {
        "summary": "Login",
        "description": "Essa rota é responsável por fazer login na API",
        "tags": ["Authentication"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Login"
              },
              "examples": {
                "Login": {
                  "value": {
                    "email": "example@mail.com",
                    "password": "senhaforte123"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "200 - Sucesso ao fazer login",
            "content": {
              "application/json": {
                "schema": {
                  "token": "string"
                },
                "examples": {
                  "Token": {
                    "value": {
                      "token": "5e6f246df54a2b48ca21cd56c7aeba4da5630de195797df9806ddba3e0b02ee9"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/talker": {
      "post": {
        "summary": "Create talker",
        "description": "Essa rota é responsável por criar um talker",
        "tags": ["Talkers"],
        "security": [{ "bearerAuth": [] }],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Talker"
              },
              "examples": {
                "Talker": {
                  "value": {
                    "name": "Danielle Santos",
                    "age": 56,
                    "talk": {
                      "watchedAt": "22/10/2019",
                      "rate": 5
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "200 - Sucesso ao criar um Talker",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Talker"
                },
                "examples": {
                  "Talker": {
                    "value": {
                      "name": "Danielle Santos",
                      "age": 56,
                      "talk": {
                        "watchedAt": "22/10/2019",
                        "rate": 5
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "400 - Campos inválidos",
            "content": {
              "application/json": {
                "schema": {
                  "token": "string"
                },
                "examples": {
                  "Name not found": {
                    "value": {
                      "message": "O campo \"name\" é obrigatório"
                    }
                  },
                  "Invalid name": {
                    "value": {
                      "message": "O \"name\" deve ter pelo menos 3 caracteres"
                    }
                  },
                  "Age not found": {
                    "value": {
                      "message": "O campo \"age\" é obrigatório"
                    }
                  },
                  "Invalid age": {
                    "value": {
                      "message": "A pessoa palestrante deve ser maior de idade"
                    }
                  },
                  "Invalid talk": {
                    "value": {
                      "message": "O campo \"talk\" é obrigatório e \"watchedAt\" e \"rate\" não podem ser vazios"
                    }
                  },
                  "Invalid date": {
                    "value": {
                      "message": "O campo \"watchedAt\" deve ter o formato \"dd/mm/aaaa\""
                    }
                  },
                  "Invalid rate": {
                    "value": {
                      "message": "O campo \"rate\" deve ser um inteiro de 1 à 5"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "401 - Erro de autenticação",
            "content": {
              "application/json": {
                "schema": {
                  "token": "string"
                },
                "examples": {
                  "Token not found": {
                    "value": {
                      "message": "Token não encontrado'"
                    }
                  },
                  "Invalid Token": {
                    "value": {
                      "message": "Token inválido"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "summary": "Lista todos os talkers",
        "description": "Essa rota é responsável por listar todos os talkers",
        "tags": ["Talkers"],
        "security": [{ "bearerAuth": [] }],
        "responses": {
          "200": {
            "sumarry": "Listar talkers",
            "description": "Lista todos os Talkers",
            "responses": {
              "200": {
                "description": "Listar todos os Talkers",
                "content": {
                  "application/json": {
                    "schema": {
                      "type": "array",
                      "properties": {
                        "name": {
                          "type": "string"
                        },
                        "age": {
                          "type": "number"
                        },
                        "id": {
                          "type": "number"
                        },
                        "talk": {
                          "type": "object",
                          "properties": {
                            "watchedAt": {
                              "type": "string"
                            },
                            "rate": {
                              "type": "number"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/talker/{id}": {
      "get": {
        "summary": "Listar talker por id",
        "description": "Essa rota é responsável por listar um talker por id",
        "tags": ["Talkers"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do Talker",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Listar talkers por id",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Talker"
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "Atualizar Talker",
        "description": "Essa rota é responsável por mudar dos dados de um talker",
        "tags": ["Talkers"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do Talker",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Talker"
              },
              "examples": {
                "Talker": {
                  "value": {
                    "name": "Danielle Santos",
                    "age": 56,
                    "talk": {
                      "watchedAt": "22/10/2019",
                      "rate": 5
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Listar talkers por id",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Talker"
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Deletar Talker",
        "description": "Essa rota é responsável por excluir um talker",
        "tags": ["Talkers"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID do Talker",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "200 - Talker removido com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "message": {
                    "type": "string"
                  }
                },
                "examples": {
                  "Sucesso ao deletar": {
                    "value": {
                      "message": "Pessoa palestrante deletada com sucesso"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/talker/search": {
      "get": {
        "summary": "Buscar Talkers pelo nome",
        "description": "Essa rota é responsável buscar Talkers pelo nome",
        "tags": ["Talkers"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "in": "query",
            "name": "q",
            "description": "Nome do Talker"
          }
        ],
        "responses": {
          "200": {
            "description": "Listar talkers",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Talker"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Login": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "Talker": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "age": {
            "type": "number"
          },
          "talk": {
            "type": "object",
            "properties": {
              "watchedAt": {
                "type": "string"
              },
              "rate": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
